# -*- coding: utf-8 -*-
"""Final project animation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Es-bqDhiRl9XXa54y7OkAKWgJXZ_PLoy
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib import rc
rc('animation', html='jshtml')
# Physical parameters
g = 9.81
M1 = 0.344
M2 =0.215
L1 =0.27
L2 = 0.18

def simulate_double_pendulum_euler(theta1_0, theta1_dot_0, theta2_0, theta2_dot_0, dt, steps):
    # Initialize arrays to store theta and omega values
    theta1 = np.zeros(steps)
    theta1_dot = np.zeros(steps)
    theta2 = np.zeros(steps)
    theta2_dot = np.zeros(steps)

    theta1[0] = theta1_0
    theta1_dot[0] = theta1_dot_0
    theta2[0] = theta2_0
    theta2_dot[0] = theta2_dot_0

    for i in range(steps-1):
        delta = theta1[i] - theta2[i]

        denom1 = L1 * (2*M1 + M2 - M2 * np.cos(2*delta))
        denom2 = L2 * (2*M1 + M2 - M2 * np.cos(2*delta))

        theta1_double_dot = (
            (-g * (2*M1 + M2) * np.sin(theta1[i])
             - M2 * g * np.sin(theta1[i] - 2*theta2[i])
             - 2 * np.sin(delta) * M2 * (theta2_dot[i]**2 * L2 + theta1_dot[i]**2 * L1 * np.cos(delta)))
            / denom1
        )

        theta2_double_dot = (
            (2 * np.sin(delta) *
             (theta1_dot[i]**2 * L1 * (M1 + M2) +
              g * (M1 + M2) * np.cos(theta1[i]) +
              theta2_dot[i]**2 * L2 * M2 * np.cos(delta)))
            / denom2
        )

        # Euler integration step
        theta1_dot[i+1] = theta1_dot[i] + theta1_double_dot * dt
        theta1[i+1] = theta1[i] + theta1_dot[i] * dt

        theta2_dot[i+1] = theta2_dot[i] + theta2_double_dot * dt
        theta2[i+1] = theta2[i] + theta2_dot[i] * dt

    return theta1, theta2

# Simulation parameters
dt = 0.01
t_max = 20
steps = int(t_max / dt)

# Initial conditions for multiple pendulums
n_pendulums = 5
base_theta1 = np.pi / 2  # 90 degrees
base_theta2 = np.pi / 2
initial_conditions = []

# Small angle differences for each pendulum
angle_diffs = [0,0.01, -0.01, 0.01, -0.01]
angle2_diffs = [0,0.01, -0.01, -0.01, 0.01]

for i in range(len(angle_diffs)):
    diff = angle_diffs[i]
    diff2 = angle2_diffs[i]
    initial_conditions.append((base_theta1 + diff, 0, base_theta2 + diff2, 0))

# Simulate all pendulums
results = []
for theta1_0, theta1_dot_0, theta2_0, theta2_dot_0 in initial_conditions:
    th1, th2 = simulate_double_pendulum_euler(theta1_0, theta1_dot_0, theta2_0, theta2_dot_0, dt, steps)
    results.append((th1, th2))

# Prepare animation
fig, ax = plt.subplots(figsize=(6,6))
ax.set_xlim(-2*(L1+L2), 2*(L1+L2))
ax.set_ylim(-2*(L1+L2), 2*(L1+L2))
ax.set_aspect('equal')
ax.grid()

lines = []
colors = plt.cm.viridis(np.linspace(0,1,n_pendulums))
for c in colors:
    line, = ax.plot([], [], 'o-', lw=1.5, alpha=0.8, color=c)
    lines.append(line)

def update(frame):
    for i, (th1, th2) in enumerate(results):
        # Compute cartesian coordinates of the two bobs
        x1 = L1 * np.sin(th1[frame])
        y1 = -L1 * np.cos(th1[frame])
        x2 = x1 + L2 * np.sin(th2[frame])
        y2 = y1 - L2 * np.cos(th2[frame])

        lines[i].set_data([0, x1, x2], [0, y1, y2])

    return lines
frame_skip = 5
ani = animation.FuncAnimation(fig, update, frames=range(0, steps, frame_skip), interval=50, blit=True)
ani

# NOTE: this was written for Colab, where `ani` on its own line renders an inline
# HTML5 animation (via rc('animation', html='jshtml') above). That does nothing in a
# plain script. To save it as a file when running locally instead, uncomment one of:
#
# ani.save('double_pendulum_animation.gif', writer='pillow', fps=20)
# ani.save('double_pendulum_animation.mp4', writer='ffmpeg', fps=20)