# -*- coding: utf-8 -*-
"""Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gjFxqfReE4x23k1dFe3-Iq0pAunCYYQX
"""

import numpy as np  # ספרייה לחישובים מתמטיים
import matplotlib.pyplot as plt  # ספרייה לציור גרפים

g = 9.81  # תאוצת הכובד
M1 = 1    # מסה של המטוטלת הראשונה
M2 = 1    # מסה של המטוטלת השנייה
L1 = 1    # אורך החוט של המטוטלת הראשונה
L2 = 1    # אורך החוט של המטוטלת השנייה

# פונקציה שמדמה את תנועת המטוטלת הכפולה באמצעות שיטת אוילר
def simulate_double_pendulum_euler(theta1_0, theta1_dot_0, theta2_0, theta2_dot_0, dt, steps):
    theta1 = np.zeros(steps)      # זווית של המטוטלת הראשונה לאורך זמן
    theta1_dot = np.zeros(steps)  # מהירות זוויתית של המטוטלת הראשונה
    theta2 = np.zeros(steps)      # זווית של המטוטלת השנייה לאורך זמן
    theta2_dot = np.zeros(steps)  # מהירות זוויתית של המטוטלת השנייה

    theta1[0] = theta1_0          # תנאי התחלה - זווית התחלתית
    theta1_dot[0] = theta1_dot_0  # תנאי התחלה - מהירות התחלתית
    theta2[0] = theta2_0
    theta2_dot[0] = theta2_dot_0

    for i in range(steps - 1):  # לולאה על כל שלבי הזמן
        difference = theta1[i] - theta2[i]  # הפרש בין הזוויות

        denom1 = L1 * (2*M1 + M2 - M2 * np.cos(2*difference))  # מכנה של נוסחת התאוצה של θ1
        denom2 = L2 * (2*M1 + M2 - M2 * np.cos(2*difference))  # מכנה של נוסחת התאוצה של θ2

        # תאוצה זוויתית של θ1 לפי משוואות תנועה
        theta1_double_dot = (
            (-g * (2*M1 + M2) * np.sin(theta1[i])
             - M2 * g * np.sin(theta1[i] - 2*theta2[i])
             - 2 * np.sin(difference) * M2 * (theta2_dot[i]**2 * L2 + theta1_dot[i]**2 * L1 * np.cos(difference)))
            / denom1
        )

        # תאוצה זוויתית של θ2 לפי משוואות תנועה
        theta2_double_dot = (
            (2 * np.sin(difference) *
             (theta1_dot[i]**2 * L1 * (M1 + M2) +
              g * (M1 + M2) * np.cos(theta1[i]) +
              theta2_dot[i]**2 * L2 * M2 * np.cos(difference)))
            / denom2
        )

        # עדכון מהירויות וזוויות לפי שיטת אוילר
        theta1_dot[i+1] = theta1_dot[i] + theta1_double_dot * dt
        theta1[i+1] = theta1[i] + theta1_dot[i] * dt

        theta2_dot[i+1] = theta2_dot[i] + theta2_double_dot * dt
        theta2[i+1] = theta2[i] + theta2_dot[i] * dt

    return theta1, theta2  # מחזיר את הזוויות של שתי המטוטלות לאורך זמן

dt = 0.001      # מרווח זמן בין כל צעד סימולציה
t_max = 50      # זמן כולל של הסימולציה
steps = int(t_max / dt)  # מספר צעדים כולל

# רשימת זוויות התחלה לבחינה
theta_degrees = [
    (30, 30),
    (30, 60),
    (30, 90),
    (30, 105),
    (30, 120),
    (45, 30),
    (45, 60),
    (45, 90),
    (45, 105),
    (45, 120),
    (60, 30),
    (60, 45),
    (60, 60),
    (60, 90),
    (60, 105),
    (60, 120),
    (75, 15),
    (75, 60),
    (75, 75),
    (75, 90),
    (90, 0),
    (90, 30),
    (90, 45),
    (90, 60),
    (90, 90),
    (120, 30),
    (120, 45),
    (120, 60),
    (120, 90),
    (120, 120)
]

delta = np.deg2rad(0.1)  # שיבוש קטן לזוויות ההתחלתיות (0.1 מעלות ברדיאנים)

results = []  # רשימת תוצאות

# מריץ סימולציה כפולה (עם ובלי שיבוש קטן) לכל זוג זוויות התחלה
for deg1, deg2 in theta_degrees:
    rad1 = np.deg2rad(deg1)  # המרה למעלות
    rad2 = np.deg2rad(deg2)
    th1_a, th2_a = simulate_double_pendulum_euler(rad1, 0, rad2, 0, dt, steps)  # סימולציה רגילה
    th1_b, th2_b = simulate_double_pendulum_euler(rad1 + delta, 0, rad2 + delta, 0, dt, steps)  # סימולציה עם שיבוש קטן
    results.append(((th1_a, th2_a), (th1_b, th2_b), deg1, deg2))  # שמירת התוצאות

# יצירת גרפים
fig, axs = plt.subplots(len(results), 1, figsize=(6, 4 * len(results)))  # תת גרפים
if len(results) == 1:
    axs = [axs]

# ציור כל זוג סימולציות
for ax, ((th1_a, th2_a), (th1_b, th2_b), deg1, deg2) in zip(axs, results):
    # באמצעות zip(axs, results) אפשר לעבור בלולאה אחת על כל זוג (ax, result) ולצייר את התוצאה המתאימה בגרף המתאים לה.
    #בלי zip
    #(for i in range(...) היה צריך לנהל אינדקסים ידנית
    # A חישוב מיקום הקצה של המסה השנייה בסימולציה
    x1_a = L1 * np.sin(th1_a)
    y1_a = -L1 * np.cos(th1_a)
    x2_a = x1_a + L2 * np.sin(th2_a)
    y2_a = y1_a - L2 * np.cos(th2_a)

    # B חישוב מיקום הקצה של המסה השנייה בסימולציה
    x1_b = L1 * np.sin(th1_b)
    y1_b = -L1 * np.cos(th1_b)
    x2_b = x1_b + L2 * np.sin(th2_b)
    y2_b = y1_b - L2 * np.cos(th2_b)

    ax.plot(x2_a, y2_a, label='Sim A')  #A ציור המסלול של סימולציה
    ax.plot(x2_b, y2_b, label='Sim B')  #B ציור המסלול של סימולציה

    ax.plot(x2_a[0], y2_a[0], 'go')         # סימון נקודת התחלה (A)
    ax.plot(x2_a[-1], y2_a[-1], 'o', color='purple')  # נקודת סיום (A)
    ax.plot(x2_b[0], y2_b[0], 'gx')         # סימון נקודת התחלה (B)
    ax.plot(x2_b[-1], y2_b[-1], 'x', color='purple')  # נקודת סיום (B)

    # חישוב המרחק בין המסלולים לאורך הזמן
    dist = np.sqrt((x2_a - x2_b)**2 + (y2_a - y2_b)**2)
    separation_indices = np.where(dist > 0.1)[0]  # מתי הם נפרדים ביותר מ-0.1

    if len(separation_indices) > 0:
        sep_idx = separation_indices[0]  # הרגע הראשון של הפרדה
        ax.plot(x2_a[sep_idx], y2_a[sep_idx], 'ko')  # סימון הפרדה במסלול A
        ax.plot(x2_b[sep_idx], y2_b[sep_idx], 'kx')  # סימון הפרדה במסלול B

    ax.set_xlabel('x')  # תווית ציר x
    ax.set_ylabel('y')  # תווית ציר y
    ax.set_title(f'Start: θ₁={deg1}°, θ₂={deg2}°')  # כותרת הגרף
    ax.legend()  # מקרא
    ax.grid()  # רשת רקע

plt.tight_layout()  # סידור הגרפים
plt.show()  # הצגת הגרפים
